  direction               = "INGRESS"
  network                 = "vpc-m-services-base"
  priority                = 1000
  project                 = "lk-mgmt-apps"
  iap_port                = ["22"]
  iap_protocol            = "tcp"
  iap_description         = "SSH access via IAP"
  iap_name                = "fw-services-base-ssh-iap"
  iap_ranges              = ["35.235.240.0/20"]
  http_port               = ["80","443"]
  http_protocol           = "tcp"
  http_description        = "HTTP access to public"
  http_name               = "fw-services-base-http-public"
  http_ranges             = ["0.0.0.0/0"]
  healthcheck_port        = []
  healthcheck_protocol    = "tcp"
  healthcheck_description = "Allow GCP Health Check probes"
  healthcheck_name        = "fw-services-base-health-check-gcp"
  healthcheck_ranges      = ["209.85.204.0/22","209.85.152.0/22","130.211.0.0/22","35.191.0.0/16"]
